PYTHON_FILE=$1.py
OUTPUT_FILE=$1.txt
EXPECTED_RESULTS=$1.results
TEMPORARY_RESULTS_FILE=$1.temporary.results

python3 $PYTHON_FILE $OUTPUT_FILE > $TEMPORARY_RESULTS_FILE
diff $EXPECTED_RESULTS $TEMPORARY_RESULTS_FILE
rm $TEMPORARY_RESULTS_FILE
